### ISSUE TITLE
Issue running swift build 

### ISSUE THREAD

**Issue by haydgately** [CreateAPI/CreateAPI#153]
pension_plan_kit/.build/checkouts/Get/Sources/Get/DataLoader.swift:156:50: error: incorrect argument label in call (have '_:didCreateTask:', expected '_:taskIsWaitingForConnectivity:')
            handlers[task]?.delegate?.urlSession?(session, didCreateTask: task)

**Comment by liamnichols** [comment]
Hmm interesting. Please can you share some information about your build environment.. Are you using Xcode or `swift build`? Which version of Xcode/Swift are you trying to build with.

> Get/Sources/Get/DataLoader.swift

This is actually part of the [Get](https://github.com/kean/get) library so it might be that we need to open an issue over there depending on what the problem is.

**Comment by haydgately** [comment]
I am using swift build and latest stable which is 14.0

**Comment by liamnichols** [comment]
Thanks, I just tried and I can replicate the same issue but this is related to [Get](https://github.com/kean/get) and not CreateAPI itself. Please could you open an issue in that repository providing the same information above? 

It looks like some things might have changed in the latest beta of Xcode. Note that CreateAPI doesn't support Get 2.0 yet so a version of Get 1.0 would also need to be released with a patch for this issue.

**Comment by liamnichols** [comment]
Actually, it looks like Get 2.x fixes the issue. But I wonder if we can get an updated version of Get 1.x that patches this issue too?

This is the required diff:

```diff
diff --git a/Sources/Get/DataLoader.swift b/Sources/Get/DataLoader.swift
index 9bfcc45..e4dca52 100644
--- a/Sources/Get/DataLoader.swift
+++ b/Sources/Get/DataLoader.swift
@@ -150,7 +150,7 @@ final class DataLoader: NSObject, URLSessionDataDelegate, URLSessionDownloadDele
         userTaskDelegate?.urlSession?(session, taskIsWaitingForConnectivity: task)
     }
 
-#if swift(>=5.7)
+#if !os(macOS) && !targetEnvironment(macCatalyst) && swift(>=5.7)
     func urlSession(_ session: URLSession, didCreateTask task: URLSessionTask) {
         if #available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, *) {
             handlers[task]?.delegate?.urlSession?(session, didCreateTask: task)
```

cc @kean

**Comment by kean** [comment]
Yes, I can release a patch for Get 1.0 as well. I'll do it later today.

**Comment by haydgately** [comment]
Amazing thanks so much! I will try when it has been released :D @kean  @liamnichols

**Comment by kean** [comment]
Should be fixed in [Get 1.0.3](https://github.com/kean/Get/releases/tag/1.0.3).

**Comment by haydgately** [comment]
I tried to reinstall CreateAPI but it is still the same version: 

Warning: create-api 0.1.0 is already installed and up-to-date.
To reinstall 0.1.0, run:
  brew reinstall create-api
  
  Is there a fix expected here for this to work?

**Comment by liamnichols** [comment]
No need to update CreateAPI, you just need to run `swift package reset` and `swift build` on the package that you had already generated and it should clone the 1.0.3 version of Get instead.

If that doesn't work, try deleting the `.swiftpm` directory to force it to update the dependencies

**Comment by haydgately** [comment]
<img width="1538" alt="Screenshot 2022-09-14 at 10 24 04" src="https://user-images.githubusercontent.com/8005325/190116042-d7ba6378-3490-4f84-a51d-eced342d670b.png">

Sorry for this, but I am struggling to get it past 1.0.2

**Comment by liamnichols** [comment]
Hmm, maybe try deleting **Package.resolved**? It might have 1.0.2 cached in there.

**Comment by haydgately** [comment]
Where would I do this sorry?

**Comment by haydgately** [comment]
<img width="961" alt="Screenshot 2022-09-14 at 14 52 45" src="https://user-images.githubusercontent.com/8005325/190173079-09a83596-af1f-473a-a164-f8d70f7b6847.png">

Thanks, a new error but one for a separate issue probably, thanks for your help :)

**Comment by liamnichols** [comment]
Well at least we're making progress 🙂 The errors look very odd to me, I'm not entirely sure what is going on here. Is the project private ? Are you able to share the generated output so I can try running it locally to reproduce the issue? 


In the meantime, I'm just adding Xcode 14 support to our CI checks to check if any errors show up - #156

**Comment by liamnichols** [comment]
I just saw your other ticket.. Will close this one and move the conversation over to #155 👍
